### ISSUE TITLE
Change the tag for desciption

### ISSUE THREAD

**Issue by 2021mt93538** [Swapnil-Pathare/Devops-Assignment-1#10]
The description "Some text about who we are and what we do" is written inside a paragraph tag p. Change the tag to the heading h2 tag.
![git issue](https://user-images.githubusercontent.com/103668459/164878655-81c24c85-8058-4fb6-a50f-9f1501466898.png)

**Comment by Swapnil-Pathare** [comment]
we are using "P" tag as that is a paragraph, closing this issue for now
